[package]
name = "common_service"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = {version="10.2.0", features=["rust_crypto"]}
actix-web = "4.12.0"

serde = "1.0.228"
serde_json = "1.0.145"